name: sip_ua
version: 0.2.0
description: A dart-lang version of the SIP UA stack.
homepage: https://github.com/cloudwebrtc/dart-sip-ua
environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  crypto: ^3.0.0
  flutter_webrtc: ^0.5.8
  parser_error: ^0.1.1
  sdp_transform: ^0.2.0
  uuid: ^3.0.1
  random_string: ^2.1.0
  logger: ^0.9.4
  intl: ^0.17.0
  recase: ^3.0.1
  path: ^1.6.4

dev_dependencies:
  test: ^1.6.7
